AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Role for EKS

# Parameters:
#   NameCluster:
#       Description: An environment name that will be prefixed to resource names
#       Type: String
      

Resources:
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EksClusterRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
        Version: '2012-10-17' 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  
  EksNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EksNodeRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
        Version: '2012-10-17' 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

Outputs:

EksClusterRoleArn:
  Description: Role EKS arn
  Value: !GetAtt EksClusterRole.Arn
  Export:
    Name: EksClusterRoleArn

